name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer install

      - name: Run Tests
        run: php artisan test

      - name: Build and Deploy
        run: |
          php artisan optimize
          php artisan migrate
          php artisan route:cache
